//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcgTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyPaste_CopyIncompleteCombis {
            get {
                return ((bool)(this["CopyPaste_CopyIncompleteCombis"]));
            }
            set {
                this["CopyPaste_CopyIncompleteCombis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyPaste_CopyIncompleteSetListSlots {
            get {
                return ((bool)(this["CopyPaste_CopyIncompleteSetListSlots"]));
            }
            set {
                this["CopyPaste_CopyIncompleteSetListSlots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyPaste_PasteDuplicatePrograms {
            get {
                return ((bool)(this["CopyPaste_PasteDuplicatePrograms"]));
            }
            set {
                this["CopyPaste_PasteDuplicatePrograms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyPaste_PasteDuplicateCombis {
            get {
                return ((bool)(this["CopyPaste_PasteDuplicateCombis"]));
            }
            set {
                this["CopyPaste_PasteDuplicateCombis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyPaste_PasteDuplicateSetListSlots {
            get {
                return ((bool)(this["CopyPaste_PasteDuplicateSetListSlots"]));
            }
            set {
                this["CopyPaste_PasteDuplicateSetListSlots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyPaste_OverwriteFilledPrograms {
            get {
                return ((bool)(this["CopyPaste_OverwriteFilledPrograms"]));
            }
            set {
                this["CopyPaste_OverwriteFilledPrograms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyPaste_OverwriteFilledCombis {
            get {
                return ((bool)(this["CopyPaste_OverwriteFilledCombis"]));
            }
            set {
                this["CopyPaste_OverwriteFilledCombis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyPaste_OverwriteFilledSetListSlots {
            get {
                return ((bool)(this["CopyPaste_OverwriteFilledSetListSlots"]));
            }
            set {
                this["CopyPaste_OverwriteFilledSetListSlots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyPaste_AutoExtendedSinglePatchSelectionPaste {
            get {
                return ((bool)(this["CopyPaste_AutoExtendedSinglePatchSelectionPaste"]));
            }
            set {
                this["CopyPaste_AutoExtendedSinglePatchSelectionPaste"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_CombiWindowWidth {
            get {
                return ((int)(this["UI_CombiWindowWidth"]));
            }
            set {
                this["UI_CombiWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_CombiWindowHeight {
            get {
                return ((int)(this["UI_CombiWindowHeight"]));
            }
            set {
                this["UI_CombiWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_PcgWindowWidth {
            get {
                return ((int)(this["UI_PcgWindowWidth"]));
            }
            set {
                this["UI_PcgWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_PcgWindowHeight {
            get {
                return ((int)(this["UI_PcgWindowHeight"]));
            }
            set {
                this["UI_PcgWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_ListGeneratorWindowWidth {
            get {
                return ((int)(this["UI_ListGeneratorWindowWidth"]));
            }
            set {
                this["UI_ListGeneratorWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_ListGeneratorWindowHeight {
            get {
                return ((int)(this["UI_ListGeneratorWindowHeight"]));
            }
            set {
                this["UI_ListGeneratorWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_SongWindowWidth {
            get {
                return ((int)(this["UI_SongWindowWidth"]));
            }
            set {
                this["UI_SongWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_SongWindowHeight {
            get {
                return ((int)(this["UI_SongWindowHeight"]));
            }
            set {
                this["UI_SongWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_M3_OS1x {
            get {
                return ((string)(this["MasterFile_M3_OS1x"]));
            }
            set {
                this["MasterFile_M3_OS1x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_KronosOS10_11 {
            get {
                return ((string)(this["MasterFile_KronosOS10_11"]));
            }
            set {
                this["MasterFile_KronosOS10_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_Oasys {
            get {
                return ((string)(this["MasterFile_Oasys"]));
            }
            set {
                this["MasterFile_Oasys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_M50 {
            get {
                return ((string)(this["MasterFile_M50"]));
            }
            set {
                this["MasterFile_M50"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_MasterFilesWindowHeight {
            get {
                return ((int)(this["UI_MasterFilesWindowHeight"]));
            }
            set {
                this["UI_MasterFilesWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_MasterFilesWindowWidth {
            get {
                return ((int)(this["UI_MasterFilesWindowWidth"]));
            }
            set {
                this["UI_MasterFilesWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_MicroStation {
            get {
                return ((string)(this["MasterFile_MicroStation"]));
            }
            set {
                this["MasterFile_MicroStation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_TritonExtreme {
            get {
                return ((string)(this["MasterFile_TritonExtreme"]));
            }
            set {
                this["MasterFile_TritonExtreme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_TritonTrClassicStudioRack {
            get {
                return ((string)(this["MasterFile_TritonTrClassicStudioRack"]));
            }
            set {
                this["MasterFile_TritonTrClassicStudioRack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_TritonKarma {
            get {
                return ((string)(this["MasterFile_TritonKarma"]));
            }
            set {
                this["MasterFile_TritonKarma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_TritonLe {
            get {
                return ((string)(this["MasterFile_TritonLe"]));
            }
            set {
                this["MasterFile_TritonLe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MasterFiles_AutoLoad {
            get {
                return ((int)(this["MasterFiles_AutoLoad"]));
            }
            set {
                this["MasterFiles_AutoLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_KronosOS15_16 {
            get {
                return ((string)(this["MasterFile_KronosOS15_16"]));
            }
            set {
                this["MasterFile_KronosOS15_16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_KronosOS2x {
            get {
                return ((string)(this["MasterFile_KronosOS2x"]));
            }
            set {
                this["MasterFile_KronosOS2x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_M3_OS20 {
            get {
                return ((string)(this["MasterFile_M3_OS20"]));
            }
            set {
                this["MasterFile_M3_OS20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyPaste_CopyPatchesFromMasterFile {
            get {
                return ((bool)(this["CopyPaste_CopyPatchesFromMasterFile"]));
            }
            set {
                this["CopyPaste_CopyPatchesFromMasterFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string UI_Language {
            get {
                return ((string)(this["UI_Language"]));
            }
            set {
                this["UI_Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double UI_MainWindowHeight {
            get {
                return ((double)(this["UI_MainWindowHeight"]));
            }
            set {
                this["UI_MainWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double UI_MainWindowWidth {
            get {
                return ((double)(this["UI_MainWindowWidth"]));
            }
            set {
                this["UI_MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UI_MainWindowTop {
            get {
                return ((double)(this["UI_MainWindowTop"]));
            }
            set {
                this["UI_MainWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UI_MainWindowLeft {
            get {
                return ((double)(this["UI_MainWindowLeft"]));
            }
            set {
                this["UI_MainWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_MainWindowState {
            get {
                return ((int)(this["UI_MainWindowState"]));
            }
            set {
                this["UI_MainWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_Krome {
            get {
                return ((string)(this["MasterFile_Krome"]));
            }
            set {
                this["MasterFile_Krome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_Kross {
            get {
                return ((string)(this["MasterFile_Kross"]));
            }
            set {
                this["MasterFile_Kross"] = value;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_Kross2
        {
            get
            {
                return ((string)(this["MasterFile_Kross2"]));
            }
            set
            {
                this["MasterFile_Kross2"] = value;
            }
        }
      
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sort_ArtistTitleSortOrder {
            get {
                return ((bool)(this["Sort_ArtistTitleSortOrder"]));
            }
            set {
                this["Sort_ArtistTitleSortOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string Sort_SplitCharacter {
            get {
                return ((string)(this["Sort_SplitCharacter"]));
            }
            set {
                this["Sort_SplitCharacter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Sort_Order {
            get {
                return ((int)(this["Sort_Order"]));
            }
            set {
                this["Sort_Order"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_TrinityV2 {
            get {
                return ((string)(this["MasterFile_TrinityV2"]));
            }
            set {
                this["MasterFile_TrinityV2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_TrinityV3 {
            get {
                return ((string)(this["MasterFile_TrinityV3"]));
            }
            set {
                this["MasterFile_TrinityV3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TrinityCategorySetA {
            get {
                return ((bool)(this["TrinityCategorySetA"]));
            }
            set {
                this["TrinityCategorySetA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Slg_DefaultOutputFolder {
            get {
                return ((string)(this["Slg_DefaultOutputFolder"]));
            }
            set {
                this["Slg_DefaultOutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CleanTimbres_WithMidiChannel {
            get {
                return ((bool)(this["CleanTimbres_WithMidiChannel"]));
            }
            set {
                this["CleanTimbres_WithMidiChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CleanTimbres_GM {
            get {
                return ((bool)(this["CleanTimbres_GM"]));
            }
            set {
                this["CleanTimbres_GM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CleanTimbres_MidiChannels {
            get {
                return ((int)(this["CleanTimbres_MidiChannels"]));
            }
            set {
                this["CleanTimbres_MidiChannels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CleanTimbres_OnlyCleanTimbre10 {
            get {
                return ((bool)(this["CleanTimbres_OnlyCleanTimbre10"]));
            }
            set {
                this["CleanTimbres_OnlyCleanTimbre10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CleanTimbres_WithMuteOn {
            get {
                return ((bool)(this["CleanTimbres_WithMuteOn"]));
            }
            set {
                this["CleanTimbres_WithMuteOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CleanTimbres_WithStatus {
            get {
                return ((bool)(this["CleanTimbres_WithStatus"]));
            }
            set {
                this["CleanTimbres_WithStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMCZV")]
        public string SortTimbres_SortKeys {
            get {
                return ((string)(this["SortTimbres_SortKeys"]));
            }
            set {
                this["SortTimbres_SortKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SortTimbres_FixedGaps {
            get {
                return ((bool)(this["SortTimbres_FixedGaps"]));
            }
            set {
                this["SortTimbres_FixedGaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SortTimbres_GapsBetweenMidiChannels {
            get {
                return ((int)(this["SortTimbres_GapsBetweenMidiChannels"]));
            }
            set {
                this["SortTimbres_GapsBetweenMidiChannels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SortTimbres_GapsBetweenKeyZones {
            get {
                return ((int)(this["SortTimbres_GapsBetweenKeyZones"]));
            }
            set {
                this["SortTimbres_GapsBetweenKeyZones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SortTimbres_Use8TimbresMax {
            get {
                return ((bool)(this["SortTimbres_Use8TimbresMax"]));
            }
            set {
                this["SortTimbres_Use8TimbresMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SortTimbres_KeepTimbre10Fixed {
            get {
                return ((bool)(this["SortTimbres_KeepTimbre10Fixed"]));
            }
            set {
                this["SortTimbres_KeepTimbre10Fixed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CleanTimbres_Statusses {
            get {
                return ((int)(this["CleanTimbres_Statusses"]));
            }
            set {
                this["CleanTimbres_Statusses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_Trinity {
            get {
                return ((string)(this["MasterFile_Trinity"]));
            }
            set {
                this["MasterFile_Trinity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingsTabIndex {
            get {
                return ((int)(this["SettingsTabIndex"]));
            }
            set {
                this["SettingsTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Edit_RenameFileWhenPatchNameChanges {
            get {
                return ((bool)(this["Edit_RenameFileWhenPatchNameChanges"]));
            }
            set {
                this["Edit_RenameFileWhenPatchNameChanges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pcgtools.mkspace.nl/Manual.pdf")]
        public string DefaultManualFolder {
            get {
                return ((string)(this["DefaultManualFolder"]));
            }
            set {
                this["DefaultManualFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterFile_KronosOS3x {
            get {
                return ((string)(this["MasterFile_KronosOS3x"]));
            }
            set {
                this["MasterFile_KronosOS3x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Slg_DefaultOutputFolderForSequencerFiles {
            get {
                return ((string)(this["Slg_DefaultOutputFolderForSequencerFiles"]));
            }
            set {
                this["Slg_DefaultOutputFolderForSequencerFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CopyPaste_IgnoreCharactersForPatchDuplication {
            get {
                return ((string)(this["CopyPaste_IgnoreCharactersForPatchDuplication"]));
            }
            set {
                this["CopyPaste_IgnoreCharactersForPatchDuplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CopyPaste_PatchDuplicationName {
            get {
                return ((int)(this["CopyPaste_PatchDuplicationName"]));
            }
            set {
                this["CopyPaste_PatchDuplicationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UI_ShowNumberOfReferencesColumn {
            get {
                return ((bool)(this["UI_ShowNumberOfReferencesColumn"]));
            }
            set {
                this["UI_ShowNumberOfReferencesColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UI_ShowWarningWhenClearingUsedPatches {
            get {
                return ((bool)(this["UI_ShowWarningWhenClearingUsedPatches"]));
            }
            set {
                this["UI_ShowWarningWhenClearingUsedPatches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int UI_ClearPatches {
            get {
                return ((int)(this["UI_ClearPatches"]));
            }
            set {
                this["UI_ClearPatches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UI_ClearPatchesFixReferences {
            get {
                return ((bool)(this["UI_ClearPatchesFixReferences"]));
            }
            set {
                this["UI_ClearPatchesFixReferences"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Settings_AutoBackupFilesEnabled {
            get {
                return ((bool)(this["Settings_AutoBackupFilesEnabled"]));
            }
            set {
                this["Settings_AutoBackupFilesEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Settings_AutoBackupFilesIntervalTime {
            get {
                return ((int)(this["Settings_AutoBackupFilesIntervalTime"]));
            }
            set {
                this["Settings_AutoBackupFilesIntervalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Settings_AutoBackupFilesMaxStorage {
            get {
                return ((int)(this["Settings_AutoBackupFilesMaxStorage"]));
            }
            set {
                this["Settings_AutoBackupFilesMaxStorage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_SongTimbresWindowHeight {
            get {
                return ((int)(this["UI_SongTimbresWindowHeight"]));
            }
            set {
                this["UI_SongTimbresWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_SongTimbresWindowWidth {
            get {
                return ((int)(this["UI_SongTimbresWindowWidth"]));
            }
            set {
                this["UI_SongTimbresWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleLinedSetListSlotDescriptions {
            get {
                return ((bool)(this["SingleLinedSetListSlotDescriptions"]));
            }
            set {
                this["SingleLinedSetListSlotDescriptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyPaste_PasteDuplicateDrumKits {
            get {
                return ((bool)(this["CopyPaste_PasteDuplicateDrumKits"]));
            }
            set {
                this["CopyPaste_PasteDuplicateDrumKits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyPaste_PasteDuplicateWaveSequences {
            get {
                return ((bool)(this["CopyPaste_PasteDuplicateWaveSequences"]));
            }
            set {
                this["CopyPaste_PasteDuplicateWaveSequences"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyPaste_OverwriteFilledDrumKits {
            get {
                return ((bool)(this["CopyPaste_OverwriteFilledDrumKits"]));
            }
            set {
                this["CopyPaste_OverwriteFilledDrumKits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyPaste_OverwriteFilledWaveSequences {
            get {
                return ((bool)(this["CopyPaste_OverwriteFilledWaveSequences"]));
            }
            set {
                this["CopyPaste_OverwriteFilledWaveSequences"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyPaste_OverwriteFilledDrumPatterns {
            get {
                return ((bool)(this["CopyPaste_OverwriteFilledDrumPatterns"]));
            }
            set {
                this["CopyPaste_OverwriteFilledDrumPatterns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyPaste_PasteDuplicateDrumPatterns {
            get {
                return ((bool)(this["CopyPaste_PasteDuplicateDrumPatterns"]));
            }
            set {
                this["CopyPaste_PasteDuplicateDrumPatterns"] = value;
            }
        }
    }
}
